### ISSUE TITLE
ImportError: cannot import name 'GPTVectorStoreIndex' from 'llama_index' (unknown location)

### ISSUE THREAD

**Issue by aarontj73** [ericmjl/llamabot#53]
After installing llamabot in a fresh conda env with python 3.9 i get the error in the title. Any fixes recommended?

**Comment by jackievaleri** [comment]
I had the same error in a fresh python3.10 conda environment. The error is because I was working with an old version of llamabot - v0.0.62. This is the version that is compatible with 3.10.

I did a fresh python3.11 conda environment and then `pip install llamabot`. This installed the latest version of llamabot, v0.4.4. The error resolved for me! So I recommend upgrading to 3.11 environment and retrying the llamabot install.

**Comment by ericmjl** [comment]
Thanks for reporting the error, @aarontj73, and thanks for chiming in, @jackievaleri! It looks like I should push a change that sets the minimum version of Python to 3.10 or 3.11, I think, which is what is tested on CI/CD.
